# .nixpacks.toml

[phases.setup]
nixPkgs = [
  "php",
  "phpPackages.composer",
  "nodejs_18",
  "npm"
]

[phases.install]
cmds = [
  "composer install --no-interaction --prefer-dist --optimize-autoloader --ignore-platform-reqs",
  "npm ci"
]

[phases.build]
cmds = [
  "chmod +x build-assets.sh",
  "./build-assets.sh"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
