# .nixpacks.toml

[phases.setup]
nixPkgs = [
  "php",
  "phpPackages.composer",
  "nodejs_18",
  "npm"
]

[phases.install]
cmds = [
  "composer install --no-interaction --prefer-dist --optimize-autoloader --ignore-platform-reqs",
  "npm ci"
]

[phases.build]
cmds = [
  "echo 'Starting build process...'",
  "pwd",
  "ls -la",
  "echo 'Node version:'",
  "node --version",
  "echo 'NPM version:'",
  "npm --version",
  "echo 'Building assets...'",
  "npm run build",
  "echo 'Build completed, checking output...'",
  "ls -la public/",
  "ls -la public/build/",
  "ls -la public/build/assets/",
  "echo 'Manifest content:'",
  "cat public/build/manifest.json",
  "echo 'Build process finished'"
]

[phases.postBuild]
cmds = [
  "php artisan config:clear",
  "php artisan cache:clear",
  "php artisan view:clear",
  "php artisan storage:link"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
