[build]
# remove nixpacks or set to docker
# builder = "nixpacks"

[deploy]
startCommand = "apache2-foreground"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[deploy.envs]
NODE_ENV = "production"